MVC/Models/EngEstViewModel.cs
using BaseEntities.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MVC.Models
{
    public class EngEstViewModel
    {
        public int IdTranslation { get; set; }
        public int IdWordEng { get; set; }
        public int IdWordEst { get; set; }
        public int? IdCategory { get; set; }
        public int? IdPart { get; set; }
        public string Example { get; set; }

        public Subcategory IdCategoryNavigation { get; set; }
        public PartOfSpeech IdPartNavigation { get; set; }
        public LangEnglish IdWordEngNavigation { get; set; }
        public LangEstonian IdWordEstNavigation { get; set; }


        //public static implicit operator EngEstViewModel(TranslationEngEst engest)
        //{
        //    return new EngEstViewModel
        //    {
        //        IdTranslation = engest.IdTranslation,
        //        IdWordEng = engest.IdWordEng,
        //        IdWordEst = engest.IdWordEst,
        //        IdCategory = engest.IdCategory,
        //        IdPart = engest.IdPart,
        //        Example = engest.Example,

        //        IdCategoryNavigation = engest.IdCategoryNavigation,
        //        IdPartNavigation = engest.IdPartNavigation,
        //        IdWordEngNavigation = engest.IdWordEngNavigation,
        //        IdWordEstNavigation = engest.IdWordEstNavigation
                
                
        //    };
        //}

        //public static implicit operator TranslationEngEst(EngEstViewModel vm)
        //{
        //    return new TranslationEngEst
        //    {
        //        IdTranslation = vm.IdTranslation,
        //        IdWordEng = vm.IdWordEng,
        //        IdWordEst = vm.IdWordEst,
        //        IdCategory = vm.IdCategory,
        //        IdPart = vm.IdPart,
        //        Example = vm.Example,

        //        IdCategoryNavigation = vm.IdCategoryNavigation,
        //        IdPartNavigation = vm.IdPartNavigation,
        //        IdWordEngNavigation = vm.IdWordEngNavigation,
        //        IdWordEstNavigation = vm.IdWordEstNavigation

        //    };
        //}
    }
}

MVC/Controllers/EngEstController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using AutoMapper;
using BaseEntities.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using MVC.Models;
using Services;
using Services.Interfaces;

namespace MVC.Controllers
{
    public class EngEstController : Controller
    {

        //private readonly EngEstService engest;
        private readonly IMapper mapper;

        private readonly IGenericTranslate<TranslationEngEst> translation;
        private readonly IGenericService<LangEnglish> langEnglish;
        private readonly IGenericService<LangEstonian> langEstonian;
        private readonly IGenericService<PartOfSpeech> part;
        private readonly IGenericService<Subcategory> sub;
        public EngEstController(IGenericTranslate<TranslationEngEst> tr, IMapper mapper,
            IGenericService<LangEnglish> langEnglish,
            IGenericService<LangEstonian> langEstonian,
             IGenericService<PartOfSpeech> part,
             IGenericService<Subcategory> sub)
        {
            //this.engest = engest;
            this.mapper = mapper;
            this.translation = tr;
            this.langEnglish = langEnglish;
            this.langEstonian = langEstonian;
            this.part = part;
            this.sub = sub;
        }

        // GET: EngEst
        [HttpGet]
        public IActionResult Index()
        {

            //if (ModelState.IsValid)
            //{
            //    var result = translation.GetByID(); authenticateService.RegisterUser(registerVM);  // implicit   
            //                                                                // conversion from RegisterViewModel to User Model  

            //    RegisterViewModel vm = result; // see implicit conversion   
            //                                   // from User model to RegisterViewModel  

            //    return View(vm);

            //}
            //return View(registerVM);

            List<EngEstViewModel> model = new List<EngEstViewModel>();
            translation.GetAll().ToList().OrderBy(x=>x.IdWordEngNavigation.Word).ToList().ForEach(x =>
            {
                //TranslationEngEst trans = translation.GetByID(x.IdTranslation);
                //EngEstViewModel vm = new EngEstViewModel();
                var stuff = mapper.Map<TranslationEngEst, EngEstViewModel>(translation.GetByID(x.IdTranslation));

                model.Add(stuff);

            });
            var wordEng = langEnglish.GetAll().ToList();
            var wordEst = langEstonian.GetAll().ToList();
            var parts = part.GetAll().ToList();
            var subs = sub.GetAll();

            ViewBag.WordEng = wordEng;
            ViewBag.WordEst = wordEst;
            ViewBag.Parts = parts;
            ViewBag.Subs = subs;


            return View(model);//model
        }

        // POST: EngEst/Create
        [HttpPost]
        //[ValidateAntiForgeryToken]
        public ActionResult Create(EngEstViewModel ee)
        {

            try
            {
                if (ModelState.IsValid)
                {
                    translation.Create(mapper.Map<EngEstViewModel, TranslationEngEst>(ee));

                
                    //TranslationEngEst trans = new TranslationEngEst();
                    //translation.Create(trans);
                    //return RedirectToAction(nameof(Index));
                }
            }
            catch
            {
                ModelState.AddModelError("", "Unable to save changes. " +
            "Try again, and if the problem persists " +
            "see your system administrator.");

            }
           return  RedirectToAction("Index");
        }
        
        // POST: EngEst/Edit/5
        [HttpPost]
        //[ValidateAntiForgeryToken]
        public ActionResult Update(EngEstViewModel ee)
        {

            //TranslationEngEst trans = new TranslationEngEst();

            translation.Update(mapper.Map<EngEstViewModel, TranslationEngEst>(ee));

            return RedirectToAction("Index");
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public void Delete(int id)
        {

            translation.Delete(id);

        }
    }
}

MVC/Views/EngEst/Index.cshtml
@model IEnumerable<EngEstViewModel>
@using MVC.Models
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<div class="row ">
    <div class="col s12">
        @foreach (var item in Model)
        {
            <h5>
                @Html.DisplayFor(modelItem => item.IdWordEngNavigation.Word)
                <span class="new badge light-green"
                      data-badge-caption=" @Html.DisplayFor(modelItem => item.IdPartNavigation.Partname)"></span>
            </h5>
            <div class="divider"></div>
            <div class="row highlighted">
                <div class="col s5 m5 l2 ">
                    <span class="new badge indigo lighten-1 category"
                          data-badge-caption=" @Html.DisplayFor(modelItem => item.IdCategoryNavigation.IdCategoryNavigation.Categoryname)"></span>
                    <br>
                    <br>
                    <span class="new badge blue category"
                          data-badge-caption=" @Html.DisplayFor(modelItem => item.IdCategoryNavigation.Subcategoryname)"></span>
                </div>
                <div class="col s7 m6 l3 definition">
                    @Html.DisplayFor(modelItem => item.IdWordEstNavigation.Word)
                </div>
                <div class="col s12 m12 l6 explanation  offset-l1 ">
                    @Html.DisplayFor(modelItem => item.Example)
                </div>
            </div>

        }

    </div>
</div>

MVC/Views/EngEst/Index2.cshtml
@model IEnumerable<EngEstViewModel>
@using MVC.Models
@{
    ViewData["Title"] = "Index";
}

<h2>Index</h2>

<table class="table table-bordered table-striped table-condensed">

    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>@Html.DisplayFor(modelItem => item.IdWordEngNavigation.Word)</td>
                <td>@Html.DisplayFor(modelItem => item.IdWordEstNavigation.Word)</td>
                <td>@Html.DisplayFor(modelItem => item.IdCategoryNavigation.Subcategoryname)</td>
                <td>
                    <a id="editUserModal" data-toggle="modal" asp-action="Update" asp-route-id="@item.IdTranslation" data-target="#modal-action-user"
                       class="btn btn-info">
                        <i class="glyphicon glyphicon-pencil"></i>  Edit
                    </a>
                    <a id="deleteUserModal" data-toggle="modal" asp-action="Delete" asp-route-id="@item.IdTranslation" data-target="#modal-action-user" class="btn btn-danger">
                        <i class="glyphicon glyphicon-trash"></i>  Delete
                    </a>
                </td>
            </tr>
        }
    </tbody>
</table>

<!--https://professorweb.ru/my/ASP_NET/mvc/level6/6_2.php-->
@using (Html.BeginForm("Create", "EngEst", FormMethod.Post))
{
<div class="modal-body form-horizontal">
    <div class="row">
        <div class="col-lg-6">
            <div class="form-group">
                <div class="col-m-6">
                    <select name="IdWordEng" required>
                        <option value="">Choose English word</option>
                        @foreach (var item in ViewBag.WordEng)
                        {
                            <option value="@item.IdWord">@item.Word</option>
                        }
                    </select>
                </div>
                <div class="col-m-6">
                    <select name="IdWordEst" required>
                        <option value="">Choose Estonian word</option>
                        @foreach (var item in ViewBag.WordEst)
                        {
                            <option value="@item.IdWord">@item.Word</option>
                        }
                    </select>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-6">
            <div class="form-group">
                <div class="col-m-6">
                    <select name="IdCategory" required>
                        <option value="">Choose subcategory</option>
                        @foreach (var item in ViewBag.Subs)
                {
                    <option value="@item.IdSubcategory">@item.Subcategoryname</option>
}
                    </select>
                </div>
                <div class="col-m-6">
                    <select name="IdPart" required>
                        <option value="">Choose part of speech</option>
                        @foreach (var item in ViewBag.Parts)
                {
                    <option value="@item.IdPart">@item.Partname</option>
}
                    </select>
                </div>
            </div>
            <div class="form-group">
                <textarea class="form-control" name="Example" rows="3"></textarea>
            </div>
            <button type="submit" class="btn btn-primary">Submit</button>
        </div>
    </div>
</div>
}

MVC/Views/EngEst/Update.cshtml
@model IEnumerable<EngEstViewModel>
@using MVC.Models

@using (Html.BeginForm("Update", "EngEst", FormMethod.Post))
{
}